"""Add tuition_fee column to Student model

Revision ID: 011ede09dc20
Revises: 2bd701e859a7
Create Date: 2025-01-08 16:04:40.342911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '011ede09dc20'
down_revision = '2bd701e859a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tuition_fee', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('tuition_fee')

    # ### end Alembic commands ###
