"""Add Student and Invoice models

Revision ID: 2bd701e859a7
Revises: a8cae59126fa
Create Date: 2025-01-08 16:01:49.511046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bd701e859a7'
down_revision = 'a8cae59126fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_fee', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('school_diary_fee', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('school_diary_fee')
        batch_op.drop_column('activity_fee')

    # ### end Alembic commands ###
