"""Update models with tuition and optional fees

Revision ID: 32d6e64116e6
Revises: 7e360aa67eac
Create Date: 2024-12-30 16:21:32.719630

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '32d6e64116e6'
down_revision = '7e360aa67eac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('fees_paid',
               existing_type=mysql.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.drop_column('optional_fees')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('optional_fees', mysql.FLOAT(), nullable=True))
        batch_op.alter_column('fees_paid',
               existing_type=mysql.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###
