"""Added optional_fees to Student model

Revision ID: 67328cc82601
Revises: b70e7bee3b74
Create Date: 2024-12-06 18:33:34.757360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67328cc82601'
down_revision = 'b70e7bee3b74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('optional_fees', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('optional_fees')

    # ### end Alembic commands ###
