"""Add tuition_fee column to Student model

Revision ID: 6fd1389036a0
Revises: 011ede09dc20
Create Date: 2025-01-08 18:04:08.863940

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6fd1389036a0'
down_revision = '011ede09dc20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('transport_mode', sa.Float(), nullable=True))
        batch_op.drop_column('transport_fee')
        batch_op.drop_column('food_fee')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food_fee', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('transport_fee', mysql.FLOAT(), nullable=True))
        batch_op.drop_column('transport_mode')
        batch_op.drop_column('food')

    # ### end Alembic commands ###
