"""Updated Student model to include fee calculation

Revision ID: 90e3e736e6f5
Revises: 67328cc82601
Create Date: 2024-12-11 11:54:04.266849

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '90e3e736e6f5'
down_revision = '67328cc82601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('amount_due', sa.Float(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('fee_item')
    op.drop_table('invoice')
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('text_books_fee', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('exercise_books_fee', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('assesment_tool_fee', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('transport_mode', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('transport_fee', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_fee', sa.Float(), nullable=True))
        batch_op.drop_column('optional_fees')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('password_reset_required')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_reset_required', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('optional_fees', mysql.FLOAT(), nullable=True))
        batch_op.drop_column('total_fee')
        batch_op.drop_column('transport_fee')
        batch_op.drop_column('transport_mode')
        batch_op.drop_column('assesment_tool_fee')
        batch_op.drop_column('exercise_books_fee')
        batch_op.drop_column('text_books_fee')
        batch_op.drop_column('food')

    op.create_table('invoice',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('student_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('total_fees', mysql.FLOAT(), nullable=False),
    sa.Column('amount_paid', mysql.FLOAT(), nullable=True),
    sa.Column('balance_due', mysql.FLOAT(), nullable=True),
    sa.Column('issue_date', mysql.DATETIME(), nullable=True),
    sa.Column('due_date', mysql.DATETIME(), nullable=False),
    sa.Column('food_fee', mysql.FLOAT(), nullable=True),
    sa.Column('optional_fees', mysql.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name='invoice_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('fee_item',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('amount', mysql.FLOAT(), nullable=False),
    sa.Column('invoice_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], name='fee_item_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('invoices')
    # ### end Alembic commands ###
