"""Updated student and invoice models with actual values

Revision ID: a8cae59126fa
Revises: ba820a1cb8f5
Create Date: 2025-01-08 15:47:02.632265

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a8cae59126fa'
down_revision = 'ba820a1cb8f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food_fee', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('assessment_tool_fee', sa.Float(), nullable=True))
        batch_op.alter_column('text_books_fee',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('exercise_books_fee',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_column('transport_mode')
        batch_op.drop_column('assesment_tool_fee')
        batch_op.drop_column('food')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('assesment_tool_fee', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('transport_mode', mysql.VARCHAR(length=20), nullable=True))
        batch_op.alter_column('exercise_books_fee',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('text_books_fee',
               existing_type=sa.Float(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
        batch_op.drop_column('assessment_tool_fee')
        batch_op.drop_column('food_fee')

    # ### end Alembic commands ###
