"""Adrenamed to fees_paid

Revision ID: ba820a1cb8f5
Revises: f48c93f34938
Create Date: 2025-01-03 18:20:18.948980

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ba820a1cb8f5'
down_revision = 'f48c93f34938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fees_paid', sa.Float(), nullable=True))
        batch_op.drop_column('amount_paid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_paid', mysql.FLOAT(), nullable=True))
        batch_op.drop_column('fees_paid')

    # ### end Alembic commands ###
